### ISSUE TITLE
Elapsed filter with load balanced logstash in Filebeat

### ISSUE THREAD

**Issue by ivasilyev-servicetitan-com** [logstash-plugins/logstash-filter-elapsed#42]
Hello.

I have Filebeat with 4 logstash servers configured with load balancing on
```
  logstash:
    # The Logstash hosts
    hosts: ["logstash1", "logstash2", "logstash3", "logstash4"]

    # Optional load balance the events between the Logstash hosts
    loadbalance: true
```
And I have logstash-filter-elapsed configured on my logstash servers.

The problem is when "start" event comes to one logstash instance, and "end" event comes to another logstash server I'm getting `elapsed_end_without_start` with no `elapsed_time calculated` (obviously).

I didn't find any notes about dealing with this filter in loadbalanced logstash env.
Are there any recommendations how this can be configured?
Or this plug in shouldn't be used in loadbalanced env? Then it makes sense to add this info into documentation.

Thanks.
